server]
#threads = -1
datadir = /tmp/snapserver
mdns_enabled = false
[stream]
source = file:///tmp/song.pcm?name=test
[http]
publish_http=false
port = 1780
[tcp-control]
enabled = true
publish_tcp = false 
publish=false
[tcp-streaming]
publish=false