[server]
#threads = -1
datadir = /tmp/snapserver
mdns_enabled = false
codec = pcm
sampleformat = 48000:16:2
[stream]
source = process:///Users/max/.local/bin/ffmpeg?log_stderr=true&params=-v 8 -re -stream_loop -1 -i /Users/max/Projects/ButterSync/song.mp3 -f s16le -acodec pcm_s16le -ar 48000 - &name=test
[http]
publish_http=false
port = 1780
[tcp-control]
enabled = true
publish_tcp = false 
publish=false
[tcp-streaming]
publish=false