from alpine:latest

RUN apk add --no-cache multirun python3 py3-pip py3-setuptools py3-gobject3 py3-gst py3-websocket-client gstreamer gstreamer-tools snapcast 
RUN python3 -m venv --upgrade-deps --system-site-packages /opt/mopidy
RUN /opt/mopidy/bin/pip install mopidy mopidy-bandcamp
RUN mkfifo /tmp/snapfifo
COPY mopidy.conf /etc/mopidy/mopidy.conf
COPY snapserver.conf /etc/snapcast/snapserver.conf

EXPOSE 6680

CMD ["multirun", "/opt/mopidy/bin/mopidy --config /etc/mopidy/mopidy.conf", "snapserver -c /etc/snapcast/snapserver.conf"]
